<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dork84vcv/image/upload/v1554453627/IMG_20190314_093721_6.jpg" alt="Mark Essien">
                        <h6>Emmanuel Ozi-yusuf</h6>
                        <p>Data Scientist</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/aee61dcbac924ed" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/EmmanuelAdeiza" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@emmanueloziyusuf" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hello, i am Emmanuel. i am a data scientist, an intendind web developer and most importantly a human. i am an intern of HNG and hoping to scale through</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Java | SQL | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
